#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

if [ ! -f settings ]; then
  echo "Error loading configuration; settings file missing."
  exit 1
fi

source ./settings

pushd /tmp
curl -o kubernetes.tar.gz -L ${KUBERNETES_RELEASE_URL}
tar -zxvf kubernetes.tar.gz
pushd kubernetes/server
tar -zxvf kubernetes-server-linux-amd64.tar.gz
popd
popd

for b in kube-apiserver kube-proxy kube-scheduler kube-controller-manager kubelet kubectl; do
  cp /tmp/kubernetes/server/kubernetes/server/bin/${b} ${b}/${b}
  chmod +x ${b}/${b}
  pushd ${b}/
  docker build -t ${b}:${KUBERNETES_VERSION} .
  rm ${b}
  popd
done
