kubelet:
  command: >
    --address=0.0.0.0
    --api-servers=http://10.240.34.178:8080
    --containerized
    --enable-server
    --machine-id-file=/rootfs/etc/machine-id
    --v=1
  image: "kelseyhightower/kubelet:0.20.0"
  net: "host"
  privileged: true
  restart: "always"
  volumes:
    - "/usr/bin/nsenter:/nsenter"
    - "/usr:/usr"
    - "/lib64:/lib64"
    - "/:/rootfs:ro"
    - "/etc/kubernetes:/etc/kubernetes"
    - "/etc/os-release:/etc/os-release"
    - "/usr/share/ca-certificates/:/etc/ssl/certs"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"
    - "/var/lib/kubelet/:/var/lib/kubelet:rw"
    - "/var/run:/var/run:rw"
proxy:
  command: >
    --logtostderr=true
    --master=http://10.240.34.178:8080
    --v=1
  image: "kelseyhightower/kube-proxy:0.20.0"
  net: "host"
  privileged: true
  restart: "always"
  volumes:
    - "/etc/kubernetes:/etc/kubernetes"
    - "/usr/share/ca-certificates:/etc/ssl/certs"
    - "/usr:/usr"
    - "/lib64:/lib64"
