etcd:
  command: >
    --advertise-client-urls http://127.0.0.1:2379 
    --data-dir /var/lib/etcd 
    --listen-client-urls http://127.0.0.1:2379 
    --listen-peer-urls http://127.0.0.1:2380 
    --name etcd0
  image: "quay.io/coreos/etcd:v2.0.12"
  net: "host"
  restart: "always"
  volumes:
    - "/var/lib/etcd:/var/lib/etcd"
    - "/usr/share/ca-certificates/:/etc/ssl/certs"
apiserver:
  command: >
    --etcd-servers=http://127.0.0.1:2379
    --insecure-bind-address=0.0.0.0
    --insecure-port=8080
    --logtostderr=true
    --service-cluster-ip-range=10.200.20.0/24
    --v=2 
  image: "kelseyhightower/kube-apiserver:0.20.0"
  net: "host"
  restart: "always"
  volumes:
    - "/etc/kubernetes:/etc/kubernetes"
    - "/usr/share/ca-certificates:/etc/ssl/certs"
    - "/var/run/kubernetes:/var/run/kubernetes"
controllermanager:
  command: >
    --logtostderr=true
    --master=http://127.0.0.1:8080
    --v=2
  image: "kelseyhightower/kube-controller-manager:0.20.0"
  net: "host"
  restart: "always"
  volumes:
    - "/etc/kubernetes:/etc/kubernetes"
    - "/usr/share/ca-certificates:/etc/ssl/certs"
scheduler:
  command: >
    --logtostderr=true
    --master=http://127.0.0.1:8080
    --v=2
  image: "kelseyhightower/kube-scheduler:0.20.0"
  net: "host"
  restart: "always"
  volumes:
    - "/etc/kubernetes:/etc/kubernetes"
    - "/usr/share/ca-certificates:/etc/ssl/certs"
